### Ping the API
GET {{baseUrl}}

### Get all hotels
GET {{baseUrl}}hotel

### Create a hotel
POST {{baseUrl}}hotel
Content-Type: application/json

{
  "name": "Hotel Helsingør",
  "address": "Strandvejen 25"
}

### Get hotel by ID
GET {{baseUrl}}hotel/1

### Update hotel
PUT {{baseUrl}}hotel/1
Content-Type: application/json

{
  "name": "Hotel Kronborg",
  "address": "Kronborgvej 1"
}

### Get rooms for hotel
GET {{baseUrl}}hotel/2/rooms

### Delete hotel
DELETE {{baseUrl}}hotel/2

---

### Add room to hotel
POST {{baseUrl}}room
Content-Type: application/json

{
  "hotelId": 2,
  "number": "555",
  "price": 9500.0
}

### Delete room
DELETE {{baseUrl}}room/36

### Log in user
POST {{baseUrl}}auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "user"
}

### Log in admin
POST {{baseUrl}}auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


### Register
POST {{baseUrl}}auth/register
Content-Type: application/json

{
  "username": "user",
  "password": "user"
}



### protected ADMIN
GET {{baseUrl}}protected/admin_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCZW5qYW1pbiBSaW5vIiwic3ViIjoidXNlciIsImV4cCI6MTc2MTI0MDY0MSwicm9sZXMiOiJVc2VyIiwidXNlcm5hbWUiOiJ1c2VyIn0.T1CnU_K1qyJoimwOEW0HZOQSQhyLVjwtNeu5RbGCoXA


### protected USER
GET {{baseUrl}}protected/user_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCZW5qYW1pbiBSaW5vIiwic3ViIjoidXNlciIsImV4cCI6MTc2MTI0MDY0MSwicm9sZXMiOiJVc2VyIiwidXNlcm5hbWUiOiJ1c2VyIn0.T1CnU_K1qyJoimwOEW0HZOQSQhyLVjwtNeu5RbGCoXA



### protected ANYONE
GET {{baseUrl}}protected/both_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCZW5qYW1pbiBSaW5vIiwic3ViIjoidXNlciIsImV4cCI6MTc2MTI0MDY0MSwicm9sZXMiOiJVc2VyIiwidXNlcm5hbWUiOiJ1c2VyIn0.T1CnU_K1qyJoimwOEW0HZOQSQhyLVjwtNeu5RbGCoXA